import type {
  DelegateWorkflowAttemptSnapshot,
  DelegateWorkflowCoordinator,
} from './workflow-coordinator';
import type {
  BoundWorkflowSelector,
  ResolvedWorkflowInput,
  SymbolicWorkflowSelector,
} from './workflow-inputs';
import {
  type AttemptIdentity,
  isTerminalWorkflowAttemptState,
} from './workflow-model';

export const WAKE_COORDINATOR_VERSION = 1 as const;
export const WAKE_ID_MAX_LENGTH = 64;
export const WAKE_MAX_SUBSCRIPTIONS = 256;
export const WAKE_MAX_PAYLOAD_SELECTORS = 8;
export const WAKE_PAYLOAD_CAPS = {
  handoffBytes: 12 * 1024,
  metadataBytes: 8 * 1024,
  viewBytes: 8 * 1024,
  aggregateBytes: 24 * 1024,
} as const;

const WAKE_ID_PATTERN = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const VIEW_NAME_PATTERN = /^[A-Za-z][A-Za-z0-9_-]{0,63}$/;
const WAKE_STATES = new Set<WakeState>([
  'pending',
  'ready',
  'queued',
  'entered',
  'cancelled',
  'blocked',
]);

/** A subscription barrier. Bare references are resolved once at registration. */
export type WakeCondition =
  | { readonly node: string }
  | { readonly all: readonly string[] }
  | { readonly any: readonly string[] };

/** Explicit, symbolic payload channels; no implicit report channel exists. */
export type WakePayloadSelector =
  | 'handoff'
  | 'metadata'
  | { readonly view: string }
  | { readonly kind: 'handoff'; readonly node?: string }
  | { readonly kind: 'metadata'; readonly node?: string }
  | { readonly kind: 'view'; readonly name: string; readonly node?: string };

export type WakePayloadKind = 'handoff' | 'metadata' | 'view';

export interface CanonicalWakePayloadSelector {
  readonly kind: WakePayloadKind;
  readonly name?: string;
  /** Exact source attempt, when the selector explicitly names one. */
  readonly node?: AttemptIdentity;
}

export type WakeState =
  | 'pending'
  | 'ready'
  | 'queued'
  | 'entered'
  | 'cancelled'
  | 'blocked';

export interface WakePayloadSource {
  /** Bounded parent handoff, never the child's exact final report. */
  readonly handoff?: string;
  /** Compact lifecycle metadata, without messages or prose. */
  readonly metadata?: Record<string, unknown>;
  /** Selected named structured views only. */
  readonly views?: Readonly<Record<string, unknown>>;
}

export interface WakePayload extends WakePayloadSource {
  /** Canonical payload grouping; keys are exact attempt identities. */
  readonly sources: Readonly<Record<AttemptIdentity, WakePayloadSource>>;
}

export interface WakeSubscriptionOptions {
  /** Stable caller-supplied identity; IDs are never generated by this model. */
  readonly id: string;
  readonly condition: WakeCondition;
  readonly payload?: readonly WakePayloadSelector[];
  /** Alias accepted at the model boundary for callers that call these selectors. */
  readonly selectors?: readonly WakePayloadSelector[];
}

export interface WakeSnapshot {
  readonly id: string;
  readonly condition: WakeCondition;
  /** Exact attempt identities captured when the subscription was registered. */
  readonly references: readonly AttemptIdentity[];
  readonly payload: readonly CanonicalWakePayloadSelector[];
  readonly state: WakeState;
  readonly createdAt: number;
  readonly readyAt?: number;
  /** Exact sources selected at the readiness transition, for recovery. */
  readonly readyReferences?: readonly AttemptIdentity[];
  readonly queuedAt?: number;
  readonly enteredAt?: number;
  readonly cancelledAt?: number;
  readonly dispatchAttempts: number;
  readonly lastDispatchFailure?: string;
  readonly reason?: string;
}

export interface WakeCoordinatorSnapshot {
  readonly version: typeof WAKE_COORDINATOR_VERSION;
  readonly wakes: readonly WakeSnapshot[];
}

export interface WakeDispatch {
  readonly wake: WakeSnapshot;
  readonly payload: WakePayload;
}

export type WakeDispatchHandler = (
  dispatch: WakeDispatch,
) => void | Promise<void>;
export type WakeListener = (wake: WakeSnapshot) => void;

export interface WakeCoordinatorOptions {
  readonly workflow: DelegateWorkflowCoordinator;
  readonly now?: () => number;
  readonly dispatch?: WakeDispatchHandler;
  readonly onChange?: () => void;
}

interface WakeRecord {
  readonly id: string;
  readonly condition: WakeCondition;
  readonly references: readonly AttemptIdentity[];
  readonly payloadSelectors: readonly CanonicalWakePayloadSelector[];
  readonly createdAt: number;
  state: WakeState;
  readyAt?: number;
  readyReferences?: readonly AttemptIdentity[];
  queuedAt?: number;
  enteredAt?: number;
  cancelledAt?: number;
  dispatchAttempts: number;
  lastDispatchFailure?: string;
  reason?: string;
  payload?: WakePayload;
  dispatchGeneration: number;
}

class WakePayloadPendingError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WakePayloadPendingError';
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function boundedReason(value: unknown): string {
  const text = value instanceof Error ? value.message : String(value);
  const normalized = text.trim() || 'Wake dispatch failed.';
  return normalized.length > 256 ? `${normalized.slice(0, 255)}…` : normalized;
}

function jsonBytes(value: unknown): number {
  return Buffer.byteLength(JSON.stringify(value) ?? '', 'utf8');
}

function validTimestamp(value: unknown): value is number {
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0;
}

function copyCondition(condition: WakeCondition): WakeCondition {
  if ('node' in condition) return Object.freeze({ node: condition.node });
  if ('all' in condition)
    return Object.freeze({ all: Object.freeze([...condition.all]) });
  return Object.freeze({ any: Object.freeze([...condition.any]) });
}

function copyPayloadSelectors(
  selectors: readonly CanonicalWakePayloadSelector[],
): readonly CanonicalWakePayloadSelector[] {
  return Object.freeze(
    selectors.map((selector) => Object.freeze({ ...selector })),
  );
}

function normalizePayloadSelector(
  selector: WakePayloadSelector,
): CanonicalWakePayloadSelector {
  if (selector === 'handoff') return Object.freeze({ kind: 'handoff' });
  if (selector === 'metadata') return Object.freeze({ kind: 'metadata' });
  if (!isRecord(selector)) throw new Error('Invalid wake payload selector.');
  const candidate = selector as Record<string, unknown>;
  const kind = candidate.kind;
  const node =
    candidate.node === undefined
      ? undefined
      : typeof candidate.node === 'string'
        ? candidate.node
        : (() => {
            throw new Error('Invalid wake payload source reference.');
          })();
  if (kind === 'handoff')
    return Object.freeze({
      kind: 'handoff',
      ...(node !== undefined ? { node } : {}),
    });
  if (kind === 'metadata')
    return Object.freeze({
      kind: 'metadata',
      ...(node !== undefined ? { node } : {}),
    });
  if (kind === 'view' && typeof candidate.name === 'string')
    return normalizeView(candidate.name, node);
  if (typeof candidate.view === 'string')
    return normalizeView(candidate.view, node);
  throw new Error('Invalid wake payload selector.');
}

function normalizeView(
  name: string,
  node?: string,
): CanonicalWakePayloadSelector {
  if (!VIEW_NAME_PATTERN.test(name))
    throw new Error('Invalid wake named view.');
  return Object.freeze({
    kind: 'view',
    name,
    ...(node !== undefined ? { node } : {}),
  });
}

function normalizePayload(
  options: WakeSubscriptionOptions,
): readonly CanonicalWakePayloadSelector[] {
  if (options.payload !== undefined && options.selectors !== undefined)
    throw new Error('Wake payload and selectors are mutually exclusive.');
  const supplied = options.payload ?? options.selectors;
  const values: readonly WakePayloadSelector[] =
    supplied === undefined ? ['handoff', 'metadata'] : supplied;
  if (!Array.isArray(values) || values.length === 0)
    throw new Error('Wake payload selectors cannot be empty.');
  if (values.length > WAKE_MAX_PAYLOAD_SELECTORS)
    throw new Error('Too many wake payload selectors.');
  const normalized = values.map(normalizePayloadSelector);
  const keys = normalized.map(
    (selector) =>
      `${selector.node ?? ''}:${selector.kind}:${selector.name ?? ''}`,
  );
  if (new Set(keys).size !== keys.length)
    throw new Error('Duplicate wake payload selectors are not allowed.');
  return copyPayloadSelectors(normalized);
}

function normalizeCondition(condition: WakeCondition): {
  condition: WakeCondition;
  references: readonly string[];
} {
  if (!isRecord(condition)) throw new Error('Invalid wake condition.');
  const keys = Object.keys(condition);
  if (keys.length !== 1) throw new Error('Wake condition must have one form.');
  if ('node' in condition && typeof condition.node === 'string')
    return {
      condition: Object.freeze({ node: condition.node }),
      references: Object.freeze([condition.node]),
    };
  for (const kind of ['all', 'any'] as const) {
    const references = (condition as Record<string, unknown>)[kind];
    if (!Array.isArray(references)) continue;
    if (references.length === 0)
      throw new Error(`Wake ${kind} condition cannot be empty.`);
    if (references.some((reference) => typeof reference !== 'string'))
      throw new Error(`Wake ${kind} condition references must be strings.`);
    if (new Set(references).size !== references.length)
      throw new Error(`Duplicate wake ${kind} references are not allowed.`);
    return {
      condition: Object.freeze({ [kind]: Object.freeze([...references]) }),
      references: Object.freeze([...references]),
    } as {
      condition: WakeCondition;
      references: readonly string[];
    };
  }
  throw new Error('Invalid wake condition.');
}

function copySnapshot(record: WakeRecord): WakeSnapshot {
  return Object.freeze({
    id: record.id,
    condition: copyCondition(record.condition),
    references: Object.freeze([...record.references]),
    payload: copyPayloadSelectors(record.payloadSelectors),
    state: record.state,
    createdAt: record.createdAt,
    readyAt: record.readyAt,
    readyReferences:
      record.readyReferences === undefined
        ? undefined
        : Object.freeze([...record.readyReferences]),
    queuedAt: record.queuedAt,
    enteredAt: record.enteredAt,
    cancelledAt: record.cancelledAt,
    dispatchAttempts: record.dispatchAttempts,
    lastDispatchFailure: record.lastDispatchFailure,
    reason: record.reason,
  });
}

function isWakeTerminal(state: WakeState): boolean {
  return state === 'entered' || state === 'cancelled' || state === 'blocked';
}

/**
 * Pure, one-shot wake state machine. It observes workflow terminal events but
 * owns neither jobs nor model-facing delivery. The dispatch callback is an
 * integration seam; entering is always an explicit acknowledgement.
 */
export class WakeCoordinator {
  readonly workflow: DelegateWorkflowCoordinator;
  private readonly now: () => number;
  private dispatchHandler?: WakeDispatchHandler;
  private readonly onChange?: () => void;
  private readonly records = new Map<string, WakeRecord>();
  private readonly listeners = new Set<WakeListener>();
  private disposed = false;
  private readonly unsubscribeWorkflow: () => void;

  constructor(options: WakeCoordinatorOptions) {
    this.workflow = options.workflow;
    this.now = options.now ?? Date.now;
    this.dispatchHandler = options.dispatch;
    this.onChange = options.onChange;
    this.unsubscribeWorkflow = this.workflow.subscribeTerminal(() =>
      this.reevaluatePending(),
    );
  }

  register(options: WakeSubscriptionOptions): WakeSnapshot {
    if (this.disposed) throw new Error('Wake coordinator is disposed.');
    this.validateId(options.id);
    if (this.records.has(options.id))
      throw new Error(`Wake ID "${options.id}" is already registered.`);
    if (this.records.size >= WAKE_MAX_SUBSCRIPTIONS)
      throw new Error('Too many wake subscriptions.');
    const normalized = normalizeCondition(options.condition);
    const references = normalized.references.map((reference) => {
      const attempt = this.workflow.require(reference);
      return attempt.identity;
    });
    if (new Set(references).size !== references.length) {
      const kind =
        'node' in normalized.condition
          ? 'node'
          : 'all' in normalized.condition
            ? 'all'
            : 'any';
      throw new Error(`Duplicate wake ${kind} references are not allowed.`);
    }
    const payloadSelectors = this.bindPayloadSelectors(
      normalizePayload(options),
      references,
    );
    const timestamp = this.now();
    const record: WakeRecord = {
      id: options.id,
      condition: this.bindCondition(normalized.condition, references),
      references: Object.freeze([...references]),
      payloadSelectors,
      createdAt: timestamp,
      state: 'pending',
      dispatchAttempts: 0,
      dispatchGeneration: 0,
    };
    // Install before evaluating: an onChange/dispatch observer may re-enter.
    this.records.set(record.id, record);
    this.emit(record);
    this.reevaluate(record);
    return copySnapshot(record);
  }

  subscribe(options: WakeSubscriptionOptions): WakeSnapshot {
    return this.register(options);
  }

  get(id: string): WakeSnapshot | undefined {
    const record = this.records.get(id);
    return record ? copySnapshot(record) : undefined;
  }

  require(id: string): WakeSnapshot {
    const record = this.records.get(id);
    if (!record) throw new Error(`Unknown wake ID "${id}".`);
    return copySnapshot(record);
  }

  list(): WakeSnapshot[] {
    return [...this.records.values()].map(copySnapshot);
  }

  snapshot(): WakeCoordinatorSnapshot {
    return Object.freeze({
      version: WAKE_COORDINATOR_VERSION,
      wakes: Object.freeze(this.list()),
    });
  }

  /** Replace the in-memory state with trusted-looking, validated metadata. */
  restore(value: unknown): void {
    if (this.disposed) throw new Error('Wake coordinator is disposed.');
    const candidate = isRecord(value) ? value : undefined;
    if (candidate?.version !== WAKE_COORDINATOR_VERSION) return;
    if (!Array.isArray(candidate.wakes)) return;
    this.records.clear();
    for (const item of candidate.wakes.slice(0, WAKE_MAX_SUBSCRIPTIONS)) {
      const record = this.parseRestoredRecord(item);
      if (record) this.records.set(record.id, record);
    }
    for (const record of this.records.values()) {
      this.emit(record);
      this.reevaluate(record);
    }
  }

  setDispatchHandler(handler: WakeDispatchHandler | undefined): void {
    this.dispatchHandler = handler;
    if (handler) {
      for (const record of this.records.values())
        if (record.state === 'ready') this.queue(record);
    }
  }

  retry(id: string): WakeSnapshot {
    const record = this.requireRecord(id);
    if (record.state !== 'ready')
      throw new Error(`Wake "${id}" is not ready for dispatch retry.`);
    this.queue(record);
    return copySnapshot(record);
  }

  retryDispatch(id: string): WakeSnapshot {
    return this.retry(id);
  }

  markEntered(id: string): WakeSnapshot {
    const record = this.requireRecord(id);
    if (record.state === 'entered') return copySnapshot(record);
    if (record.state !== 'queued')
      throw new Error(`Wake "${id}" is not queued for entry.`);
    record.state = 'entered';
    record.enteredAt = this.now();
    record.payload = undefined;
    this.emit(record);
    return copySnapshot(record);
  }

  enter(id: string): WakeSnapshot {
    return this.markEntered(id);
  }

  cancel(id: string, reason = 'Wake subscription cancelled.'): WakeSnapshot {
    const record = this.requireRecord(id);
    if (isWakeTerminal(record.state)) return copySnapshot(record);
    record.state = 'cancelled';
    record.cancelledAt = this.now();
    record.reason = boundedReason(reason);
    record.payload = undefined;
    record.dispatchGeneration++;
    this.emit(record);
    return copySnapshot(record);
  }

  subscribeChanges(listener: WakeListener): () => void {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.unsubscribeWorkflow();
    this.listeners.clear();
  }

  private validateId(id: string): void {
    if (
      typeof id !== 'string' ||
      id.length === 0 ||
      id.length > WAKE_ID_MAX_LENGTH ||
      !WAKE_ID_PATTERN.test(id)
    )
      throw new Error(
        `Invalid wake ID "${String(id)}": use lowercase kebab-case.`,
      );
  }

  private bindPayloadSelectors(
    selectors: readonly CanonicalWakePayloadSelector[],
    references: readonly AttemptIdentity[],
  ): readonly CanonicalWakePayloadSelector[] {
    const bound = selectors.map((selector) => {
      if (selector.node === undefined) return selector;
      const attempt = this.workflow.require(selector.node);
      if (!references.includes(attempt.identity))
        throw new Error(
          `Wake payload source "${attempt.identity}" is not a condition reference.`,
        );
      return Object.freeze({ ...selector, node: attempt.identity });
    });
    for (let left = 0; left < bound.length; left++)
      for (let right = left + 1; right < bound.length; right++) {
        const first = bound[left];
        const second = bound[right];
        if (!first || !second) continue;
        if (
          first.kind !== second.kind ||
          first.name !== second.name ||
          (first.node !== undefined &&
            second.node !== undefined &&
            first.node !== second.node)
        )
          continue;
        throw new Error('Duplicate wake payload selectors are not allowed.');
      }
    return copyPayloadSelectors(bound);
  }

  private bindCondition(
    condition: WakeCondition,
    references: readonly string[],
  ): WakeCondition {
    if ('node' in condition)
      return Object.freeze({ node: references[0] ?? '' });
    if ('all' in condition)
      return Object.freeze({ all: Object.freeze([...references]) });
    return Object.freeze({ any: Object.freeze([...references]) });
  }

  private requireRecord(id: string): WakeRecord {
    const record = this.records.get(id);
    if (!record) throw new Error(`Unknown wake ID "${id}".`);
    return record;
  }

  private reevaluatePending(): void {
    for (const record of this.records.values()) this.reevaluate(record);
  }

  private reevaluate(record: WakeRecord): void {
    if (record.state === 'ready' && !record.payload) {
      try {
        record.payload = this.resolvePayload(
          record,
          record.readyReferences ?? this.terminalReferences(record),
        );
      } catch (error) {
        if (error instanceof WakePayloadPendingError) {
          record.state = 'pending';
          record.readyReferences = undefined;
          this.emit(record);
          return;
        }
        record.state = 'blocked';
        record.reason = boundedReason(error);
        this.emit(record);
        return;
      }
      if (this.dispatchHandler) this.queue(record);
      return;
    }
    if (record.state !== 'pending') return;
    const terminal = this.terminalReferences(record);
    const satisfied =
      'node' in record.condition
        ? terminal[0] === record.references[0]
        : 'all' in record.condition
          ? terminal.length === record.references.length
          : terminal.length > 0;
    if (!satisfied) return;
    try {
      record.payload = this.resolvePayload(record, terminal);
    } catch (error) {
      if (error instanceof WakePayloadPendingError) return;
      record.state = 'blocked';
      record.reason = boundedReason(error);
      this.emit(record);
      return;
    }
    record.readyReferences = Object.freeze([...terminal]);
    record.state = 'ready';
    record.readyAt = this.now();
    this.emit(record);
    if (this.dispatchHandler) this.queue(record);
  }

  private terminalReferences(record: WakeRecord): AttemptIdentity[] {
    return record.references.filter((identity) => {
      const attempt = this.workflow.get(identity);
      return attempt !== undefined && this.isTerminalAttempt(attempt);
    });
  }

  private isTerminalAttempt(attempt: DelegateWorkflowAttemptSnapshot): boolean {
    return isTerminalWorkflowAttemptState(attempt.state);
  }

  private resolvePayload(
    record: WakeRecord,
    readyReferences: readonly AttemptIdentity[],
  ): WakePayload {
    const sourceValues = new Map<AttemptIdentity, WakePayloadSource>();
    const used = new Set<string>();
    for (const selector of record.payloadSelectors) {
      const sources =
        selector.node === undefined ? readyReferences : [selector.node];
      if (sources.length === 0)
        throw new WakePayloadPendingError('Wake payload has no ready source.');
      if (
        selector.node !== undefined &&
        !readyReferences.includes(selector.node)
      )
        throw new WakePayloadPendingError(
          `Wake payload source "${selector.node}" is not terminal yet.`,
        );
      for (const identity of sources) {
        const key = `${identity}:${selector.kind}:${selector.name ?? ''}`;
        if (used.has(key))
          throw new Error('Duplicate wake payload selectors are not allowed.');
        used.add(key);
        const attempt = this.workflow.get(identity);
        if (!attempt || !this.isTerminalAttempt(attempt))
          throw new WakePayloadPendingError(
            `Wake payload source "${identity}" is not terminal yet.`,
          );
        const symbolic: SymbolicWorkflowSelector = {
          node: identity,
          ...(selector.kind === 'handoff'
            ? { include: ['handoff'] as const }
            : selector.kind === 'metadata'
              ? { include: ['metadata'] as const }
              : {
                  include: ['metadata'] as const,
                  view: selector.name,
                }),
        };
        const bound: BoundWorkflowSelector = Object.freeze({
          selector: Object.freeze(symbolic),
          identity,
        });
        const resolved = this.workflow.resolveBoundWorkflowInputs([bound]);
        const selected = resolved.inputs.find(
          (candidate: ResolvedWorkflowInput) =>
            candidate.kind === selector.kind,
        );
        if (!selected)
          throw new Error(`Wake payload ${selector.kind} is unavailable.`);
        const current = sourceValues.get(identity) ?? {};
        let next: WakePayloadSource;
        if (selector.kind === 'handoff') {
          if (typeof selected.value !== 'string')
            throw new Error('Wake handoff payload is unavailable.');
          if (
            Buffer.byteLength(selected.value, 'utf8') >
            WAKE_PAYLOAD_CAPS.handoffBytes
          )
            throw new Error('Wake handoff payload exceeds its bounded limit.');
          next = { ...current, handoff: selected.value };
        } else if (selector.kind === 'metadata') {
          if (
            selected.value === undefined ||
            jsonBytes(selected.value) > WAKE_PAYLOAD_CAPS.metadataBytes
          )
            throw new Error('Wake metadata payload exceeds its bounded limit.');
          next = {
            ...current,
            metadata: selected.value as Record<string, unknown>,
          };
        } else {
          if (
            selected.value === undefined ||
            jsonBytes(selected.value) > WAKE_PAYLOAD_CAPS.viewBytes
          )
            throw new Error(
              `Wake view "${selector.name}" exceeds its bounded limit.`,
            );
          next = {
            ...current,
            views: {
              ...(current.views ?? {}),
              [selector.name ?? '']: selected.value,
            },
          };
        }
        sourceValues.set(identity, next);
      }
    }
    const sources = Object.fromEntries(
      [...sourceValues.entries()].map(([identity, source]) => [
        identity,
        Object.freeze(source),
      ]),
    ) as Record<AttemptIdentity, WakePayloadSource>;
    if (jsonBytes(sources) > WAKE_PAYLOAD_CAPS.aggregateBytes)
      throw new Error('Wake payload exceeds its bounded aggregate limit.');
    const frozenSources = Object.freeze(sources);
    const sourceKeys = Object.keys(sources);
    if (sourceKeys.length !== 1)
      return Object.freeze({ sources: frozenSources });
    const only = sources[sourceKeys[0] ?? ''];
    return Object.freeze({
      sources: frozenSources,
      ...(only?.handoff !== undefined ? { handoff: only.handoff } : {}),
      ...(only?.metadata !== undefined ? { metadata: only.metadata } : {}),
      ...(only?.views !== undefined ? { views: only.views } : {}),
    });
  }

  private queue(record: WakeRecord): void {
    if (record.state !== 'ready' || !this.dispatchHandler) return;
    if (!record.payload) {
      try {
        record.payload = this.resolvePayload(
          record,
          record.readyReferences ?? this.terminalReferences(record),
        );
      } catch (error) {
        if (error instanceof WakePayloadPendingError) {
          record.state = 'pending';
          record.readyReferences = undefined;
          this.emit(record);
          return;
        }
        record.state = 'blocked';
        record.reason = boundedReason(error);
        this.emit(record);
        return;
      }
    }
    record.state = 'queued';
    record.queuedAt = this.now();
    record.dispatchAttempts++;
    const generation = ++record.dispatchGeneration;
    const payload = record.payload;
    if (!payload) {
      record.state = 'blocked';
      record.reason = 'Wake payload was unavailable at dispatch.';
      this.emit(record);
      return;
    }
    this.emit(record);
    if (
      record.state !== 'queued' ||
      record.dispatchGeneration !== generation ||
      !this.dispatchHandler
    )
      return;
    let result: void | Promise<void>;
    try {
      result = this.dispatchHandler({ wake: copySnapshot(record), payload });
    } catch (error) {
      this.dispatchFailed(record, generation, error);
      return;
    }
    void Promise.resolve(result).catch((error) => {
      this.dispatchFailed(record, generation, error);
    });
  }

  private dispatchFailed(
    record: WakeRecord,
    generation: number,
    error: unknown,
  ): void {
    if (record.dispatchGeneration !== generation || record.state !== 'queued')
      return;
    record.state = 'ready';
    record.lastDispatchFailure = boundedReason(error);
    record.reason = record.lastDispatchFailure;
    record.payload = undefined;
    this.emit(record);
  }

  private parseRestoredRecord(value: unknown): WakeRecord | undefined {
    if (!isRecord(value)) return undefined;
    const id = value.id;
    if (typeof id !== 'string') return undefined;
    try {
      this.validateId(id);
    } catch {
      return undefined;
    }
    if (!validTimestamp(value.createdAt) || !isRecord(value.condition))
      return undefined;
    let normalized: { condition: WakeCondition; references: readonly string[] };
    let payloadSelectors: readonly CanonicalWakePayloadSelector[];
    try {
      normalized = normalizeCondition(value.condition as WakeCondition);
      const references = normalized.references.map((reference) => {
        const attempt = this.workflow.require(reference);
        // Restored refs must already be exact and must not silently bind latest.
        if (attempt.identity !== reference) throw new Error('not exact');
        return attempt.identity;
      });
      normalized = {
        condition: this.bindCondition(normalized.condition, references),
        references: Object.freeze(references),
      };
      if (!Array.isArray(value.payload)) return undefined;
      const restoredSelectors = normalizePayload({
        id,
        condition: normalized.condition,
        payload: value.payload as readonly WakePayloadSelector[],
      });
      for (const selector of restoredSelectors)
        if (selector.node !== undefined) {
          const attempt = this.workflow.require(selector.node);
          if (attempt.identity !== selector.node) throw new Error('not exact');
        }
      payloadSelectors = this.bindPayloadSelectors(
        restoredSelectors,
        normalized.references,
      );
    } catch {
      return undefined;
    }
    if (this.records.has(id)) return undefined;
    const state = value.state;
    if (typeof state !== 'string' || !WAKE_STATES.has(state as WakeState))
      return undefined;
    let readyReferences: readonly AttemptIdentity[] | undefined;
    try {
      if (state === 'ready' || state === 'queued') {
        if (value.readyReferences !== undefined) {
          if (
            !Array.isArray(value.readyReferences) ||
            value.readyReferences.length === 0
          )
            return undefined;
          const restored = value.readyReferences.map((reference) => {
            if (typeof reference !== 'string')
              throw new Error('invalid ready source');
            const attempt = this.workflow.require(reference);
            if (
              attempt.identity !== reference ||
              !normalized.references.includes(attempt.identity)
            )
              throw new Error('invalid ready source');
            return attempt.identity;
          });
          if (new Set(restored).size !== restored.length) return undefined;
          readyReferences = Object.freeze(restored);
        } else {
          // Older entries may not have captured readiness sources. Recompute
          // only from the already-exact condition refs; never bind a bare alias.
          readyReferences = Object.freeze(
            normalized.references.filter((reference) => {
              const attempt = this.workflow.get(reference);
              return attempt !== undefined && this.isTerminalAttempt(attempt);
            }),
          );
        }
      }
    } catch {
      return undefined;
    }
    const record: WakeRecord = {
      id,
      condition: normalized.condition,
      references: normalized.references,
      payloadSelectors,
      createdAt: value.createdAt,
      state: state === 'queued' ? 'ready' : (state as WakeState),
      readyAt: validTimestamp(value.readyAt) ? value.readyAt : undefined,
      readyReferences,
      queuedAt: validTimestamp(value.queuedAt) ? value.queuedAt : undefined,
      enteredAt: validTimestamp(value.enteredAt) ? value.enteredAt : undefined,
      cancelledAt: validTimestamp(value.cancelledAt)
        ? value.cancelledAt
        : undefined,
      dispatchAttempts:
        typeof value.dispatchAttempts === 'number' &&
        Number.isSafeInteger(value.dispatchAttempts) &&
        value.dispatchAttempts >= 0 &&
        value.dispatchAttempts <= 1000
          ? value.dispatchAttempts
          : 0,
      // Failure/cancellation prose is deliberately not trusted from a session
      // entry; the state and timestamps are enough to recover delivery safely.
      lastDispatchFailure: undefined,
      reason: undefined,
      dispatchGeneration: 0,
    };
    if (record.state === 'entered' && record.enteredAt === undefined)
      return undefined;
    if (record.state === 'cancelled' && record.cancelledAt === undefined)
      return undefined;
    return record;
  }

  private emit(record: WakeRecord): void {
    const snapshot = copySnapshot(record);
    this.onChange?.();
    for (const listener of this.listeners) {
      try {
        listener(snapshot);
      } catch {
        // A delivery observer cannot break the one-shot state machine.
      }
    }
  }
}

export function createWakeCoordinator(
  options: WakeCoordinatorOptions,
): WakeCoordinator {
  return new WakeCoordinator(options);
}
