/** Contracts exposed by the dashboard daemon to HTTP, SSE, and browsers. */

export {
  MAX_COMPOSER_COMMAND_ARGUMENT_HINT,
  MAX_COMPOSER_COMMAND_DESCRIPTION,
  MAX_COMPOSER_COMMAND_NAME,
  MAX_COMPOSER_COMMANDS,
  MAX_TEXT,
} from './limits.js';

export type {
  ArchiveThreadCommand,
  CancelCommand,
  CheckoutActionCommand,
  CheckoutReviewCommand,
  CommandId,
  ProjectAdoptCommand,
  ProjectCreateCommand,
  RetryCommand,
  SessionAdoptCommand,
  ThreadCreateCommand,
} from './orchestration-commands.js';
export {
  ArchiveThreadCommandSchema,
  CancelCommandSchema,
  CheckoutActionCommandSchema,
  CheckoutReviewCommandSchema,
  CommandIdSchema,
  ProjectAdoptCommandSchema,
  ProjectCreateCommandSchema,
  RetryCommandSchema,
  SessionAdoptCommandSchema,
  ThreadCreateCommandSchema,
} from './orchestration-commands.js';
export type {
  Checkout,
  CheckoutKind,
  CheckoutStatus,
  CheckoutSummary,
  CommandReceipt,
  ModelSelection,
  Project,
  ProjectStatus,
  ProjectSummary,
  Run,
  RunMode,
  RunStatus,
  RunSummary,
  RuntimeProvider,
  Thread,
  ThreadStatus,
  ThreadSummary,
} from './orchestration-contracts.js';
export {
  CheckoutKindSchema,
  CheckoutSchema,
  CheckoutStatusSchema,
  CheckoutSummarySchema,
  CommandReceiptSchema,
  ModelSelectionSchema,
  ProjectSchema,
  ProjectStatusSchema,
  ProjectSummarySchema,
  RunModeSchema,
  RunSchema,
  RunStatusSchema,
  RunSummarySchema,
  RuntimeProviderSchema,
  ThreadSchema,
  ThreadStatusSchema,
  ThreadSummarySchema,
} from './orchestration-contracts.js';
export {
  parseArchiveThreadCommand,
  parseCancelCommand,
  parseCheckout,
  parseCheckoutActionCommand,
  parseCheckoutReviewCommand,
  parseProject,
  parseProjectAdoptCommand,
  parseProjectCreateCommand,
  parseRetryCommand,
  parseRun,
  parseSessionAdoptCommand,
  parseThread,
  parseThreadCreateCommand,
  tryParseArchiveThreadCommand,
  tryParseCancelCommand,
  tryParseCheckout,
  tryParseCheckoutActionCommand,
  tryParseCheckoutReviewCommand,
  tryParseProject,
  tryParseProjectAdoptCommand,
  tryParseProjectCreateCommand,
  tryParseRetryCommand,
  tryParseRun,
  tryParseSessionAdoptCommand,
  tryParseThread,
  tryParseThreadCreateCommand,
} from './orchestration-parsers.js';
export {
  parseBrowserSnapshot,
  parseComposerCommandCatalogue,
  parseDashboardEventEnvelope,
  parseDashboardMessage,
  parseDashboardStreamMessage,
  parseSessionApiResponse,
  parseSessionRenameRequest,
  parseStartRuntimeRequest,
  tryParseBrowserSnapshot,
  tryParseComposerCommandCatalogue,
  tryParseDashboardEventEnvelope,
  tryParseDashboardMessage,
  tryParseDashboardStreamMessage,
  tryParseSessionApiResponse,
  tryParseSessionRenameRequest,
  tryParseStartRuntimeRequest,
  validateSessionName,
  validateSessionRenameRequest,
  validateStartRuntimeRequest,
} from './parsers.js';
export type {
  BridgeEventEnvelope,
  BrowserMessage,
  BrowserSnapshot,
  ComposerCommandCatalogue,
  ComposerCommandEntry,
  ComposerCommandSource,
  ComposerCommandsResponse,
  DashboardEventEnvelope,
  DashboardMessage,
  DashboardSessionIndexStreamRecord,
  DashboardSnapshotResponse,
  DashboardSnapshotStream,
  DashboardStreamMessage,
  EventEnvelope,
  NotificationEvent,
  SessionApiResponse,
  SessionHistory,
  SessionIndexEntry,
  SessionProjection,
  SessionRenameRequest,
  SessionResponse,
  SessionSnapshotResponse,
  StartRuntimeRequest,
  WorkspaceTarget,
} from './schemas.js';
export {
  BridgeEventEnvelopeSchema,
  BrowserMessageSchema,
  BrowserSnapshotSchema,
  ComposerCommandCatalogueSchema,
  ComposerCommandEntrySchema,
  ComposerCommandSourceSchema,
  ComposerCommandsResponseSchema,
  DASHBOARD_SUPPORTED_BUILTIN_COMMANDS,
  DASHBOARD_SUPPORTED_BUILTINS,
  DashboardEventEnvelopeSchema,
  DashboardMessageSchema,
  DashboardSessionIndexStreamRecordSchema,
  DashboardSessionIndexStreamSchema,
  DashboardSnapshotResponseSchema,
  DashboardSnapshotStreamSchema,
  DashboardStreamMessageSchema,
  EventEnvelopeSchema,
  NotificationEventSchema,
  SessionApiResponseSchema,
  SessionHistorySchema,
  SessionProjectionSchema,
  SessionRenameRequestSchema,
  SessionResponseSchema,
  SessionSnapshotResponseSchema,
  StartRuntimeRequestSchema,
  WorkspaceTargetSchema,
} from './schemas.js';
export {
  deriveSessionTitle,
  firstUserMessageText,
  normalizeSessionTitle,
  SESSION_NAME_MAX_LENGTH,
  SESSION_TITLE_MAX_LENGTH,
  workspaceForPath,
  workspaceSourcePriority,
} from './semantic.js';
