/** Contracts exposed by the dashboard daemon to HTTP, SSE, and browsers. */

export type {
  Checkout,
  CheckoutKind,
  CheckoutStatus,
  CheckoutSummary,
  CommandReceipt,
  ModelSelection,
  Project,
  ProjectStatus,
  ProjectSummary,
  Run,
  RunMode,
  RunStatus,
  RunSummary,
  RuntimeProvider,
  Thread,
  ThreadStatus,
  ThreadSummary,
} from './orchestration-contracts.js';
export {
  CheckoutKindSchema,
  CheckoutSchema,
  CheckoutStatusSchema,
  CheckoutSummarySchema,
  CommandReceiptSchema,
  ModelSelectionSchema,
  ProjectSchema,
  ProjectStatusSchema,
  ProjectSummarySchema,
  RunModeSchema,
  RunSchema,
  RunStatusSchema,
  RunSummarySchema,
  RuntimeProviderSchema,
  ThreadSchema,
  ThreadStatusSchema,
  ThreadSummarySchema,
} from './orchestration-contracts.js';
export {
  parseCheckout,
  parseProject,
  parseRun,
  parseThread,
  tryParseCheckout,
  tryParseProject,
  tryParseRun,
  tryParseThread,
} from './orchestration-parsers.js';
export {
  parseBrowserSnapshot,
  parseDashboardEventEnvelope,
  parseDashboardMessage,
  parseDashboardStreamMessage,
  parseSessionApiResponse,
  parseSessionRenameRequest,
  parseStartRuntimeRequest,
  tryParseBrowserSnapshot,
  tryParseDashboardEventEnvelope,
  tryParseDashboardMessage,
  tryParseDashboardStreamMessage,
  tryParseSessionApiResponse,
  tryParseSessionRenameRequest,
  tryParseStartRuntimeRequest,
  validateSessionName,
  validateSessionRenameRequest,
  validateStartRuntimeRequest,
} from './parsers.js';
export type {
  BridgeEventEnvelope,
  BrowserMessage,
  BrowserSnapshot,
  DashboardEventEnvelope,
  DashboardMessage,
  DashboardSnapshotResponse,
  DashboardSnapshotStream,
  DashboardStreamMessage,
  EventEnvelope,
  NotificationEvent,
  SessionApiResponse,
  SessionIndexEntry,
  SessionProjection,
  SessionRenameRequest,
  SessionResponse,
  SessionSnapshotResponse,
  StartRuntimeRequest,
  WorkspaceTarget,
} from './schemas.js';
export {
  BridgeEventEnvelopeSchema,
  BrowserMessageSchema,
  BrowserSnapshotSchema,
  DashboardEventEnvelopeSchema,
  DashboardMessageSchema,
  DashboardSnapshotResponseSchema,
  DashboardSnapshotStreamSchema,
  DashboardStreamMessageSchema,
  EventEnvelopeSchema,
  NotificationEventSchema,
  SessionApiResponseSchema,
  SessionProjectionSchema,
  SessionRenameRequestSchema,
  SessionResponseSchema,
  SessionSnapshotResponseSchema,
  StartRuntimeRequestSchema,
  WorkspaceTargetSchema,
} from './schemas.js';
export {
  deriveSessionTitle,
  normalizeSessionTitle,
  SESSION_NAME_MAX_LENGTH,
  SESSION_TITLE_MAX_LENGTH,
  workspaceForPath,
  workspaceSourcePriority,
} from './semantic.js';
