/**
 * Lexical data for activity-group titles.
 *
 * Keep language-specific vocabulary here so title.ts can stay focused on
 * recognising narration and composing a readable label.
 */

/** English strong verbs that the regular "-ing" to "-ed" rule gets wrong. */
export const IRREGULAR_PAST_TENSE: Readonly<Record<string, string>> = {
  Beginning: 'Began',
  Binding: 'Bound',
  Breaking: 'Broke',
  Bringing: 'Brought',
  Building: 'Built',
  Casting: 'Cast',
  Catching: 'Caught',
  Choosing: 'Chose',
  Cutting: 'Cut',
  Dealing: 'Dealt',
  Digging: 'Dug',
  Drawing: 'Drew',
  Feeding: 'Fed',
  Finding: 'Found',
  Getting: 'Got',
  Giving: 'Gave',
  Hiding: 'Hid',
  Hitting: 'Hit',
  Holding: 'Held',
  Keeping: 'Kept',
  Leading: 'Led',
  Leaving: 'Left',
  Letting: 'Let',
  Losing: 'Lost',
  Making: 'Made',
  Meaning: 'Meant',
  Overwriting: 'Overwrote',
  Putting: 'Put',
  Reading: 'Read',
  Rebuilding: 'Rebuilt',
  Rereading: 'Reread',
  Rerunning: 'Reran',
  Resetting: 'Reset',
  Rewriting: 'Rewrote',
  Running: 'Ran',
  Seeing: 'Saw',
  Sending: 'Sent',
  Setting: 'Set',
  Shutting: 'Shut',
  Spending: 'Spent',
  Spinning: 'Spun',
  Splitting: 'Split',
  Spreading: 'Spread',
  Sticking: 'Stuck',
  Taking: 'Took',
  Thinking: 'Thought',
  Throwing: 'Threw',
  Undoing: 'Undid',
  Understanding: 'Understood',
  Writing: 'Wrote',
};

/**
 * Russian first-person narration to the masculine completed form used by a
 * settled group. Russian present tense cannot be reversed reliably from its
 * ending, and a natural completed label often changes aspect: "Сравниваю"
 * reads as "Сравнил", not merely "Сравнивал". Future narration such as
 * "Сделаю" is included for the same reason.
 *
 * The vocabulary is intentionally coding-agent-specific. Unknown words stay
 * untouched rather than receiving a plausible-looking but incorrect form.
 */
export const RUSSIAN_PAST_TENSE: Readonly<Record<string, string>> = {
  Адаптирую: 'Адаптировал',
  Анализирую: 'Проанализировал',
  Валидирую: 'Провалидировал',
  Возвращаю: 'Вернул',
  Восстанавливаю: 'Восстановил',
  Воспроизвожу: 'Воспроизвёл',
  Выбираю: 'Выбрал',
  Выясняю: 'Выяснил',
  Выявляю: 'Выявил',
  Выполняю: 'Выполнил',
  Генерирую: 'Сгенерировал',
  Готовлю: 'Подготовил',
  Декодирую: 'Декодировал',
  Делегирую: 'Делегировал',
  Десериализую: 'Десериализовал',
  Диагностирую: 'Диагностировал',
  Добавляю: 'Добавил',
  Документирую: 'Задокументировал',
  Дорабатываю: 'Доработал',
  Завершаю: 'Завершил',
  Закрепляю: 'Закрепил',
  Закрываю: 'Закрыл',
  Записываю: 'Записал',
  Запускаю: 'Запустил',
  Защищаю: 'Защитил',
  Измеряю: 'Измерил',
  Изменяю: 'Изменил',
  Изучаю: 'Изучил',
  Интегрирую: 'Интегрировал',
  Исправляю: 'Исправил',
  Исследую: 'Исследовал',
  Ищу: 'Искал',
  Классифицирую: 'Классифицировал',
  Кодирую: 'Закодировал',
  Коммичу: 'Закоммитил',
  Компилирую: 'Скомпилировал',
  Конфигурирую: 'Сконфигурировал',
  Координирую: 'Скоординировал',
  Копирую: 'Скопировал',
  Локализую: 'Локализовал',
  Меняю: 'Изменил',
  Настраиваю: 'Настроил',
  Начинаю: 'Начал',
  Обнаруживаю: 'Обнаружил',
  Обрабатываю: 'Обработал',
  Обновляю: 'Обновил',
  Объединяю: 'Объединил',
  Объясняю: 'Объяснил',
  Определяю: 'Определил',
  Оптимизирую: 'Оптимизировал',
  Оркестрирую: 'Оркестрировал',
  Осматриваю: 'Осмотрел',
  Останавливаю: 'Остановил',
  Откатываю: 'Откатил',
  Откладываю: 'Отложил',
  Открываю: 'Открыл',
  Отключаю: 'Отключил',
  Отлаживаю: 'Отладил',
  Отменяю: 'Отменил',
  Отправляю: 'Отправил',
  Оформляю: 'Оформил',
  Оцениваю: 'Оценил',
  Очищаю: 'Очистил',
  Передаю: 'Передал',
  Переименовываю: 'Переименовал',
  Перезапускаю: 'Перезапустил',
  Перемещаю: 'Переместил',
  Переношу: 'Перенёс',
  Переписываю: 'Переписал',
  Перепроверяю: 'Перепроверил',
  Перестраиваю: 'Перестроил',
  Перехожу: 'Перешёл',
  Пишу: 'Написал',
  Планирую: 'Спланировал',
  Повторяю: 'Повторил',
  Подготавливаю: 'Подготовил',
  Подключаю: 'Подключил',
  Подтверждаю: 'Подтвердил',
  Покрываю: 'Покрыл',
  Получаю: 'Получил',
  Преобразую: 'Преобразовал',
  Применяю: 'Применил',
  Приступаю: 'Приступил',
  Проверяю: 'Проверил',
  Провожу: 'Провёл',
  Продолжаю: 'Продолжил',
  Продумываю: 'Продумал',
  Прогоняю: 'Прогнал',
  Проектирую: 'Спроектировал',
  Просматриваю: 'Просмотрел',
  Профилирую: 'Спрофилировал',
  Публикую: 'Опубликовал',
  Разбираю: 'Разобрал',
  Разбираюсь: 'Разобрался',
  Разворачиваю: 'Развернул',
  Разрабатываю: 'Разработал',
  Разделяю: 'Разделил',
  Расширяю: 'Расширил',
  Редактирую: 'Отредактировал',
  Реализую: 'Реализовал',
  Рефакторю: 'Отрефакторил',
  Сверяю: 'Сверил',
  Сделаю: 'Сделал',
  Сериализую: 'Сериализовал',
  Синхронизирую: 'Синхронизировал',
  Сканирую: 'Просканировал',
  Собираю: 'Собрал',
  Создаю: 'Создал',
  Сохраняю: 'Сохранил',
  Сопоставляю: 'Сопоставил',
  Сравниваю: 'Сравнил',
  Тестирую: 'Протестировал',
  Удаляю: 'Удалил',
  Улучшаю: 'Улучшил',
  Упрощаю: 'Упростил',
  Устанавливаю: 'Установил',
  Устраняю: 'Устранил',
  Уточняю: 'Уточнил',
  Фиксирую: 'Зафиксировал',
  Форматирую: 'Отформатировал',
  Формирую: 'Сформировал',
  Читаю: 'Прочитал',
};

/** Intent and setup verbs that should not dominate real work in a composition. */
export const META_VERBS: ReadonlySet<string> = new Set([
  'Planning',
  'Preparing',
  'Considering',
  'Deciding',
  'Determining',
  'Clarifying',
  'Thinking',
  'Weighing',
  'Планирую',
  'Готовлю',
  'Продумываю',
  'Определяю',
  'Уточняю',
  'Сделаю',
]);
